name: mssql2022-posh5-docker

on: # push, pr, nightly, and on demand, for all branches 
  # push:
  #   branches-ignore:  # Prevents duplicate runs on PRs
  #     - release
  pull_request:  # Ensures PRs to main must pass the check
    branches:
      - release                      
  # schedule:
  #   - cron: '0 3 * * *' 
  workflow_dispatch:
  workflow_call:  # This enables the workflow to be called from other workflows
  repository_dispatch:
    types: [daily-validation]  # Listens for dispatch events, which can trigger this workflow automatically on regular schedules
jobs:
  run-autopilot-sql22-psh5:
    runs-on: windows-latest
    name: Run-Autopilot-sql22-psh5
    environment: 'build-posh5'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start SQL Server (Windows container)
        shell: pwsh
        run: |
          Write-Host "Pulling SQL Server image..."
          docker pull mcr.microsoft.com/windows/server:ltsc2025

          Write-Host "Starting SQL Server container..."
          docker run -d --rm `
            --name $env:CONTAINER_NAME `
            -e "ACCEPT_EULA=Y" `
            -e "SA_PASSWORD=DatabaseDevOps!" `
            -p "1433:1433" `
            mcr.microsoft.com/windows/server:ltsc2025

          Write-Host "Waiting 60 seconds for SQL Server to initialize..."
          Start-Sleep -Seconds 60

      # --- Verify SQL Server is running ---
      - name: Check SQL connectivity
        shell: pwsh
        run: |
          Write-Host "Checking SQL Server status..."
          $result = sqlcmd -S "localhost,$env:DB_PORT" -U sa -P $env:SA_PASSWORD -Q "SELECT @@VERSION"
          if (-not $?) {
            throw "SQL Server not reachable"
          }
          Write-Host "SQL Server online:`n$result"

          # Set environment variables for later steps
          echo "dbUser=sa" >> $env:GITHUB_ENV
          echo "dbPassword=DatabaseDevOps!" >> $env:GITHUB_ENV
          echo "instance=localhost,1433" >> $env:GITHUB_ENV

      - name: Run Autopilot for TDM in PowerShell 5
        shell: powershell
        env:
          REDGATE_LICENSING_PERMIT: ${{ secrets.REDGATE_LICENSING_PERMIT }}
        run: |
          Write-Output 'Running Autopilot for TDM...'
          .\Run-Autopilot.ps1 -configFile "Autopilot-Configuration_Automation.conf" `
            -sqlUser '${{ env.dbUser }}' `
            -sqlPassword '${{ env.dbPassword }}' `
            -sqlInstance '${{ env.instance }}' `
            -trustCert $true `
            -encryptConnection $false `
            -autoContinue -skipAuth -iAgreeToTheRedgateEula

      - name: Validate Results (Autopilot Databases)
        shell: powershell
        if: ${{ always() }}
        run: |
          if (-not (Get-Module -ListAvailable -Name dbatools)) {
            Install-Module dbatools -Scope CurrentUser -AllowClobber -Force
          }
          Set-DbatoolsConfig -FullName sql.connection.trustcert -Value $true
          Set-DbatoolsConfig -FullName sql.connection.encrypt -Value $false
          $SqlCredential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList ${{ env.dbUser }}, (ConvertTo-SecureString ${{ env.dbPassword }} -AsPlainText -Force)

          $totalInvoices = (Invoke-DbaQuery -SqlInstance '${{ env.instance }}' -Database Autopilot_Treated -Query "SELECT COUNT(*) AS TotalInvoices FROM dbo.Invoice;" -SqlCredential $SqlCredential).TotalInvoices
          Write-Output "Total Invoices: $totalInvoices"
          if ($totalInvoices -ne 87) {
            Write-Error "rgsubset did not run successfully"
            exit 1
          }

          $invoice326City = (Invoke-DbaQuery -SqlInstance '${{ env.instance }}' -Database Autopilot_Treated -Query "SELECT BillingCity FROM dbo.Invoice WHERE InvoiceId = 326" -SqlCredential $SqlCredential).BillingCity
          Write-Output "BillingCity: $invoice326City"
          if ($invoice326City -like "Stockholm") {
            Write-Error "rganonymize did not run successfully"
            exit 1
          }

      - name: Cleanup SQL Server container
        if: ${{ always() }}
        shell: powershell
        run: |
          docker stop sql2022-autopilot
          docker rm sql2022-autopilot
